site_name: Nicolas Bohorquez
site_description: Nicolas Bohorquez Personal Website
site_author: Nicolas Bohorquez
site_url: https://nicolasbohorquez.netlify.com/

pages:
    - Home: index.md
    - About: about.md
    - CV: cv.md

theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'deep orange'
  font:
    text: 'Confortaa'
    code: 'Inconsolata'
  logo:
    icon: 'extension'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/nickmancol'
    - type: 'twitter'
      link: 'https://twitter.com/nickmancol'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/nickmancol'

repo_name: 'nickmancol/website'
repo_url: 'https://github.com/nickmancol/website'
